database_engine: MYSQL # POSTGRESQL | MYSQL

dns_format: ${EnvironmentName}.${DnsDomain}
hostname: postgres-proxy

users:
  default:
    secret_arn_parameter: SecretCredentials
    iam_auth: REQUIRED # REQUIRED | DISABLED